name: Automate build and release to docker hub
on:
  pull_request:
    branches: [ "master" ]
    types:
     - closed

jobs:
  build:
    # Build only merged PRs
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        run: |
          docker buildx rm
          docker buildx create --use --name webhook-sentry-builder
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_REPO }}:$(git rev-parse --short HEAD) -t ${{ secrets.DOCKERHUB_REPO }}:latest --file Dockerfile .

